### ISSUE TITLE
ElsaDashboard javascript issue after migrating from 2.13 to 2.14

### ISSUE THREAD

**Issue by zetic-be** [elsa-workflows/elsa-core#4847]
Hello,

I just migrated from Elsa 2.13 to 2.14. 
It has solved compilation warnings due to migration to .NET 8, thank you.
However, there is an issue now with loading the dashboard on the client-side:

p-e37496bc.js:2 Uncaught (in promise) TypeError: r.originalAdapter.call is not a function
    at e (p-e37496bc.js:2:897)
    at async Object.list (p-04c30d61.js:1:4811)
    at async se.componentWillLoad (p-23353c0b.entry.js:1:21264)

![image](https://github.com/elsa-workflows/elsa-core/assets/40064735/084d1939-f39b-4971-a75f-91a52820da0b)
![image](https://github.com/elsa-workflows/elsa-core/assets/40064735/236001c9-d514-4e94-bd5b-ae82f49cb367)
![image](https://github.com/elsa-workflows/elsa-core/assets/40064735/deda8c6a-6166-402d-95f7-8455dc10563c)

**Comment by liuliang-wt** [comment]
I also encountered the same problem, any help?

**Comment by ester-ka-sap** [comment]
I also have this issue. would be happy to hear about any workaround or solution to this.
![image](https://github.com/elsa-workflows/elsa-core/assets/154805186/218b5d9c-c803-4676-85a5-667be1ddc193)

**Comment by liuliang-wt** [comment]
@SipkeSchoorstraRTL  any idea?

**Comment by Chryssie** [comment]
Seems to be related to emileber/axios-middleware#62 simply put, [emileber/axios-middleware](https://github.com/emileber/axios-middleware) doesn't work with Axios ≥ 1 as `axios.defaults.adaptor` used to be a function and now it's an array of strings.

**Comment by zetic-be** [comment]
Might be a good idea to automate UI testing for early discovery.

**Comment by mohdali** [comment]
My bad, I overlooked this while making the release. I think the reason is this PR https://github.com/elsa-workflows/elsa-core/commit/3e16e6a053445d3879a15f92081e9555ef82959b. I will try to reverse it by selecting a compatible axios version < 1.2.0 and make a fix release.

**Comment by mohdali** [comment]
Should be fixed with 2.14.1 https://github.com/elsa-workflows/elsa-core/releases/tag/2.14.1
